// MyProject/roll_tool/src/pages/home/index.tsx
import style from "./index.module.scss";
import videoSource from "../../assets/video/bg_video.mp4";
import { RefObject, useEffect, useRef, useState } from "react";
interface Ball {
  el: HTMLDivElement;
  x: number;
  y: number;
  dx: number;
  dy: number;
}
const Home = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const animationId = useRef<number | null>(null);
  const videoRef: RefObject<HTMLVideoElement | null> = useRef(null);
  const divItemRef = useRef<any[]>([]);
  const people = [
    "梁以宸",
    "王艺恒",
    "魏子欣",
    "胡峻恺",
    "张航",
    "马佳宁",
    "马玥婷",
    "王建博",
    "刘佳佳",
    "魏馨源",
    "张洛萌",
    "郭展言",
    "马嘉森",
    "崔浩桐",
    "庞翊彬",
    "赵文睿",
    "马浩鑫",
    "岳静淑",
    "张宸博",
    "花子煊",
    "马正宇",
    "崔轶群",
    "商子宁",
    "孔令轩",
    "李思涵",
    "周梓轩",
    "赵心怡",
    "孙泽宇",
    "韩明杰",
    "谢佳乐",
  ];

  // 初始化小球数据
  // useEffect(() => {
  //   if (!container || items.length === 0) return;
  //
  //   const containerWidth = container.clientWidth;
  //   const containerHeight = container.clientHeight;
  //   const SIZE = 80;
  //   const SPEED = 6;
  //
  //   ballsRef.current = items.map((el) => ({
  //     el,
  //     x: Math.random() * (containerWidth - SIZE),
  //     y: Math.random() * (containerHeight - SIZE),
  //     dx: (Math.random() - 0.5) * SPEED,
  //     dy: (Math.random() - 0.5) * SPEED,
  //   }));
  // }, []);

  useEffect(() => {
    if (!containerRef || divItemRef.current.length === 0) return;

    const containerWidth = containerRef.current!.clientWidth;
    const containerHeight = containerRef.current!.clientHeight;
    const SIZE = 80;
    const SPEED = 6;

    console.log("divItemRef.current", divItemRef.current);

    divItemRef.current = divItemRef.current.map((el) => {
      return {
        el,
        x: Math.random() * (containerWidth - SIZE),
        y: Math.random() * (containerHeight - SIZE),
        dx: (Math.random() - 0.5) * SPEED,
        dy: (Math.random() - 0.5) * SPEED,
      };
    });
  }, []);

  // 动画函数
  const animate = () => {
    const container = containerRef.current;
    if (!container) return;

    const containerWidth = container.clientWidth;
    const containerHeight = container.clientHeight;
    const SIZE = 80;
    const SPEED = 6;

    // const divDOMs = document.querySelectorAll(`.${style.home_main_item}`);
    //

    divItemRef.current.forEach((ball: any) => {
      ball.dx = (Math.random() - 0.5) * SPEED;
      ball.dy = (Math.random() - 0.5) * SPEED;

      ball.x += ball.dx;
      ball.y += ball.dy;

      // 边界检测
      if (ball.x <= 0 || ball.x >= containerWidth - SIZE) ball.dx *= -1;
      if (ball.y <= 0 || ball.y >= containerHeight - SIZE) ball.dy *= -1;

      ball.el.style.transform = `translate(${ball.x}px, ${ball.y}px)`;
    });

    // animationId.current = requestAnimationFrame(animate);
  };
  const startHandle = () => {
    setIsPlaying((prev) => {
      const next = !prev;

      if (next) {
        videoRef.current?.play();
        animate();
      } else {
        videoRef.current?.pause();
        cancelAnimationFrame(animationId.current);
      }

      return next;
    });
  };

  return (
    <div className={style.home}>
      <div onClick={startHandle} className={style.startBtn}>
        {isPlaying ? "暂停" : "开始"}
      </div>

      <video
        ref={videoRef}
        style={{ width: "100%", height: "100%" }}
        src={videoSource}
      />

      <main ref={containerRef} className={style.home_main}>
        {people.map((item, index) => (
          <div
            key={item}
            ref={(el) => (divItemRef.current[index] = el)}
            className={style.home_main_item}
          >
            {item}
          </div>
        ))}
      </main>
    </div>
  );
};

export default Home;

// MyProject/roll_person_tool/src/components/Home.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import VideoSource from '../assets/video/bg_video_new.mp4'
const isPlaying = ref(false);
const videoRef = ref<HTMLVideoElement | null>(null);
const singlePersonDOMList = ref<NodeListOf<Element> | null>(null);
const containerRef=ref<HTMLDivElement | null>(null);
const people = ref([
  "梁以宸",
  "王艺恒",
  "魏子欣",
  "胡峻恺",
  "张航",
  "马佳宁",
  "马玥婷",
  "王建博",
  "刘佳佳",
  "魏馨源",
  "张洛萌",
  "郭展言",
  "马嘉森",
  "崔浩桐",
  "庞翊彬",
  "赵文睿",
  "马浩鑫",
  "岳静淑",
  "张宸博",
  "花子煊",
  "马正宇",
  "崔轶群",
  "商子宁",
  "孔令轩",
  "李思涵",
  "周梓轩",
  "赵心怡",
  "孙泽宇",
  "韩明杰",
  "谢佳乐",
]);

let animationId: number | null = null;

// 动画函数
const animate = () => {
  const count =  people.value.length;
  let angle = 0;

  function updatePositions() {


    const a = 580; // 横轴（x）半径
    const b = 400; // 纵轴（y）半径

    singlePersonDOMList.value!.forEach((img:any, i) => {
      const theta = angle + (2 * Math.PI * i) / count;
      const x = a * Math.cos(theta);
      const y = b * Math.sin(theta);

      img.style.transform = `translate(${x + 630}px, ${y + 270}px)`;
      img.style.zIndex = Math.floor(100 + y); // 层级变化增强视觉深度
    });

    angle += 0.01; // 控制转速
    animationId= requestAnimationFrame(updatePositions);
  }
  updatePositions();
};

const startHandle = () => {
  isPlaying.value = !isPlaying.value;

  if (isPlaying.value) {
    videoRef.value?.play();
    animate();
  } else {
    videoRef.value?.pause();

    cancelAnimationFrame(animationId as number);
  }
};

const initPosition=()=>{
  const count =  people.value.length;
  let angle = 0;
  const a = 580; // 横轴（x）半径
  const b = 400; // 纵轴（y）半径

  singlePersonDOMList.value!.forEach((img:any, i) => {
    const theta = angle + (2 * Math.PI * i) / count;
    const x = a * Math.cos(theta);
    const y = b * Math.sin(theta);

    img.style.transform = `translate(${x + 630}px, ${y + 270}px)`;
    img.style.zIndex = Math.floor(100 + y); // 层级变化增强视觉深度
  });
}
onMounted(() => {
  singlePersonDOMList.value = document.querySelectorAll(".home_main_item");
  initPosition()



});
</script>

<template>
  <div class="home">
    <div @click="startHandle" class="startBtn">
      {{ isPlaying ? "暂停" : "开始" }}
    </div>

    <video
        ref="videoRef"
        loop
        style="width: 100%; height: 100%"
        :src="VideoSource"
    />

    <main class="home_main" ref="containerRef" >
      <div v-for="item in people" :key="item" class="home_main_item">
        <img class="home_main_item_avator"  src="../assets/images/pic.jpg"  alt="pic"/>
        <span>{{item}}</span>
      </div>
    </main>
  </div>
</template>

<style lang="scss" scoped>
.home {
  width: 100%;
  height: 97vh;
  position: relative;

  .startBtn {
    width: 50px;
    height: 50px;
    border: 1px solid blue;
    text-align: center;
    line-height: 50px;
    cursor: pointer;
    position: absolute;
    z-index: 20;
  }

  &_main {
    width: 70%;
    height: 70%;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%)  rotateX(20deg);
    &_item {
      width: 100px;
      height: 100px;
      transition: all ease-in-out 0.1s;
      position: absolute;
      display: flex;
      flex-direction: column;
      &_avator {
        width: 80px;
        height: 80px;
        border-radius: 50%;
      }
      span {
        color: white;
      }
    }
  }
}
</style>
